[project]
name = "ctr-prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.14"
dependencies = [
    "duckdb>=1.4.3",
    "matplotlib>=3.10.8",
    "notebook>=7.5.2",
    "polars>=1.37.1",
    "scipy>=1.15.3",
]
